version: '3.1' 
services:
  spark-storage:
    build: ./spark-storage
    container_name: spark-storage
    volumes:
      - ./data/hadoop:/home/hadoop/mydata
  spark-master:
    build: ./spark
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
      - 18080:18080
      - 2022:22
    environment:
      - SPARK_MODE=MASTER
  spark-worker:
    build: ./spark
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=WORKER
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORE=2
      - SPARK_WORKER_MEMORY=3G
    scale: 3
