version: '3.1' 
services:
  hadoop:
    build: ./hadoop
    container_name: hadoop
    volumes:
      - ./data/hadoop:/home/hadoop/mydata
    env_file:
      - ./hadoop.env
  spark-master:
    build: ./spark
    container_name: spark-master
    ports:
      - 10080:8080
      - 7077:7077
      - 18080:18080
    env_file:
      - ./hadoop.env
    environment:
      - SPARK_MODE=MASTER
  spark-worker:
    build: ./spark
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=WORKER
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ./hadoop.env
    scale: 1
